-- AlterTable
ALTER TABLE "memberships" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "tasks" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "workspaces" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
